### ISSUE TITLE
Update docs for refactor!: add processor builder and transform buidler

### ISSUE THREAD

**Issue by sunng87** [GreptimeTeam/docs#1170] opened 2024-09-05 02:54 UTC
A document change request is generated from https://github.com/GreptimeTeam/greptimedb/pull/4571

**Comment by paomian** [comment] 2024-10-24 07:19
I think this issue is a duplicate of that. https://github.com/GreptimeTeam/docs/issues/1108

**Closed by paomian** 2024-10-24 07:19 UTC
